document.write('<meta charset="UTF-8">');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('<meta http-equiv="X-UA-Compatible" content="ie=edge">');
document.write('<meta name="description" content="陳巧萱的個人作品集展示網站。擅長前端網頁開發與設計，熟悉HTML、CSS、Javascript和JQuery語法之應用，熱愛切版並以CSS3製作特效，知悉如何修改WordPress模板以達到客製化需求。">');
document.write('<meta name="keywords" content="個人作品集,陳巧萱,CiaoSyuanChen,網頁設計,前端網頁開發,前端網頁工程,前端網頁設計">');
document.write('<link rel="icon" href="img/icon/icon-home-red.png" type="image/x-icon" />');
document.write('<link rel="stylesheet" href="css/swiper.css">');
document.write('<link rel="stylesheet" href="css/css.css">');
document.write('<link rel="stylesheet" href="css/aos.css">');
document.write('<script src="https://code.jquery.com/jquery-3.3.1.js"></script>');
document.write('<script src="js/main.js"></script>');
document.write('<script src="js/aos.js"></script>');
