var valPorject = [
    {
        "d-val-porject": "大發金服 活動頁",//專案名稱
        "d-val-category": [//專案分類
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "金融" },
            { "category": "活動網站" },
        ],
        "d-val-skill": [//使用/支援技術
            { "image": "img/icon/icon-html-red2.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/icon-js-red.png", "title": "JavaScript" },
        ],
        "d-val-charge": "網頁開發（切版,功能,特效等）。",//負責項目
        "d-val-exp": "這個網站比較有挑戰性的地方大概是滾動數字的部分以及程式設定的部分，程式是設定每日的累積人數以及每日更新所剩數量，以JavaScript撰寫。此站為單頁式，配合視覺做出來的網站。不使用第三方套件寫出一個功能和特效是非常需要有一定基礎的，這個網站是很好的練習。",//專案心得
        "d-val-link": "",//查看網站
    },
    {
        "d-val-porject": "AI人工智能彩票整合平台系统",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Wordpress" },
            { "category": "博奕" },
            { "category": "形象網站" },
        ],
        "d-val-skill": [
            { "image": "img/icon/icon-wp2.png", "title": "Wordpress" },
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "Wordpress樣式環境調整,切版與外掛調用,JQ和JQ功能製作與網站管理",
        "d-val-exp": "此站是我出社會後第二個大型專案，配合各個部門以及較長的行程規劃。我主要負責前端功能製作、切版和部分Wordpress外掛設定與串接。在製作這個站點的時候，因為等待的時間較長，我會先將資料與所需工具準備好，因為不是第一次做大型的Wordpress網站所以在外掛的對接與選擇上也會比較上手。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "新濠皇璽會",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "飯店" },
            { "category": "形象網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "切版,JQ與JS製作",
        "d-val-exp": "這個專案是仿站，配合博弈市場所延伸出的網站。這個網站是我到公司的第一個網站很多功能和細節都是慢慢摸索，也因為都是靠自己製作所以也學習到很多技巧。以前不懂得優化自己的工作速度，現在要做什麼功能都知道可以用什麼第三方組件快速達到效果。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "UltraEGaming 奧創娛樂",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Wordpress" },
            { "category": "博奕" },
            { "category": "形象網站" },
        ],
        "d-val-skill": [
            { "image": "img/icon/icon-wp2.png", "title": "Wordpress" },
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "Wordpress樣式環境調整,切版與外掛調用,JQ和JQ功能製作與網站管理",
        "d-val-exp": "此站類似資訊站，主要在推廣平台產品和發文章，這是我出社會後第一個大型專案，學習到跨部門溝通，例如：如何將自己的技術與不熟此領域的人溝通，互相傾聽彼此的建議以及互相幫忙配合來完成專案。這個站點使用許多Wordpress的外掛所以我也學習到如何使用各個插件串接。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "點點盈",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "金融" },
            { "category": "資訊網站" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
        ],
        "d-val-charge": "切版,JQ與JS功能製作與卷軸動畫設定",
        "d-val-exp": "這個專案是仿站，練習作品。學習如何製作出當滾輪滾動的時候播放動畫的效果，製作出一個比較精細的網站。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "錢進牛股",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "金融" },
            { "category": "形象網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "切版,JQ與JS製作",
        "d-val-exp": "在SEO部門會需要做很多類似這種的推廣網站，為了增加瀏覽器的收錄，這個網站即是為了推廣QQ號碼。比較特別的地方是這個網站手機和電腦版本是分為兩個網站，不是以RWD的方式下去切。原因是企劃希望手機版可以呈現像APP的樣子為了不要讓頁面太長讓使用者感到乏味，只列出最精簡的功能。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "88老虎",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Wordpress" },
            { "category": "靜態獨立站" },
            { "category": "博弈" },
            { "category": "形象網站" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
        ],
        "d-val-charge": "Wordpress樣式環境調整,適應不同架構之網站調整,切版與外掛調用,JQ和JQ功能製作與網站管理",
        "d-val-exp": "這個網站一共做了兩種架構，一個是以Wordpress為後台來製作此站，需要將Wordpress樣式的環境調整和以仿站為皮製作出可以有後台發文功能的站點。另一個是獨立的靜態網站，兩種架構皆由我負責切版與前端的效果製作。而手機版是直接跳去別的頁面，所以此網站並沒有RWD。為什麼會需要分成兩種架構的原因是，我們沒有後台人員，需要依靠Wordpress發文章的功能來替網站做每日update的功能。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "UltraEGaming 廣告專案",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Wordpress" },
            { "category": "博弈" },
            { "category": "活動網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/icon-wp2.png", "title": "Wordpress" },
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "HTML+CSS切版",
        "d-val-exp": "這個網站是為了提供UltraEGaming品牌的廣告方案所製作的網站，所以直接附屬在UltraEGaming底下。由我獨立製作與視覺配合做成此站。如果要說遇到困難的話，大概就是表格的問題，表格在手機呈現方式有限，要怎麼設定讓手機可以呈現完整內容又不會造成使用者的不便正是這次的研究項目之一。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "大發金服 導覽頁",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "金融" },
            { "category": "目錄網站" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
        ],
        "d-val-charge": "MIP技術研究,切版與優化網頁利於SEO",
        "d-val-exp": "此站特別的地方是依照SEO部門的需求以MIP（Mobile Instant Pages）語法架構下去切版製作，為了要讓大陸的手機瀏覽器能夠加速下載此網站。使用MIP架構切版有先研究1-3天的時間，了解此語法的規則並改用他們的方式來寫網站。雖然功能上有所限制，因為這個架構不接受客製化的JS，但是以一般的網站來說這些語法還是夠用的。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "大發金服 導覽頁",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "金融" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
        ],
        "d-val-charge": "HTML+CSS切版",
        "d-val-exp": "SEO部門會有很多網址放這類型的網站，將流量導入主要的網站。此站是為了要推廣大發金服品牌所做的網頁，由視覺設計好頁面後再由我這邊做切版實體化的動作。整個風格以大陸那邊習慣為主，因為是做大陸市場的關西。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "錢進牛股 金融論壇",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Discuz論壇" },
            { "category": "金融" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
        ],
        "d-val-charge": "Discuz論壇研究,大陸論壇資訊收集,HTML與CSS技術支援區塊",
        "d-val-exp": "這個網站是我第一次使用Discuz架構來製作網站，所以研究了一段時間了解他後台的用法和一些論壇相關的使用方式。這個網站我主要負責前端版塊的配置，Discuz論壇本身自己就有工具可以切區塊而我所要做的是針對切出來的區塊做樣式和細節的調整。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "百家樂娛樂城",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "博弈" },
            { "category": "形象網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "網頁視覺設計,製圖(Banner),切版與管理網站",
        "d-val-exp": "這個專案的視覺和網站開發是由我獨立製作。以往都是我和視覺互相配合製作網站這次由於時間較緊迫的緣故改將網站的設計由我負責，在製作的過程中因為設計和開發都是我自己所以更能明白區塊如何表達節省了不少時間。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "百家樂娛樂城",
        "d-val-category": [
            { "category": "網站" },
            { "category": "靜態獨立站" },
            { "category": "博弈" },
            { "category": "形象網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "網頁視覺設計,製圖(Banner),切版與管理網站",
        "d-val-exp": "這個專案的視覺和網站開發是由我獨立製作。以往都是我和視覺互相配合製作網站這次由於時間較緊迫的緣故改將網站的設計由我負責，在製作的過程中因為設計和開發都是我自己所以更能明白區塊如何表達節省了不少時間。",
        "d-val-link": "",
    },
    {
        "d-val-porject": "鳳凰國際",
        "d-val-category": [
            { "category": "網站" },
            { "category": "Worpress" },
            { "category": "直播網站" },
            { "category": "形象網站" },
            { "category": "RWD" },
        ],
        "d-val-skill": [
            { "image": "img/icon/icon-wp2.png", "title": "Wordpress" },
            { "image": "img/icon/awdawd.png", "title": "HTML5/HTML" },
            { "image": "img/icon/icon-css2.png", "title": "CSS3/CSS" },
            { "image": "img/icon/aw-js-red.png", "title": "JavaScript" },
            { "image": "img/icon/icon-jq-red.png", "title": "jQuery" },
            { "image": "img/icon/icon-rwd.png", "title": "RWD" },
        ],
        "d-val-charge": "Wordpress樣式環境調整,切版與外掛調用",
        "d-val-exp": "宣導活動時間與介紹各個主播的網站，配合視覺切版行成此站。此站，無Demo因為已經收了，在Wordpress的架構所以只有截圖沒有檔案可供下載。",
        "d-val-link": "",
    },
]